#!/bin/bash
# Script to be use through nautilus
# Create a hard link of the selected file(s)/folder(s)

# Nautilus variables
# NAUTILUS_SCRIPT_SELECTED_FILE_PATHS
#    newline-delimited paths for selected files (only if local) 
# NAUTILUS_SCRIPT_SELECTED_URIS
#    newline-delimited URIs for selected files 
# NAUTILUS_SCRIPT_CURRENT_URI
#    current location 
# NAUTILUS_SCRIPT_WINDOW_GEOMETRY
#    position and size of current window 
# https://help.ubuntu.com/community/NautilusScriptsHowto
#
#

echo "${NAUTILUS_SCRIPT_SELECTED_FILE_PATHS}" | while read file; do
		# Should be refactored
		if [ -f "${file}" ]; then
			filename=$(basename "${file}")
			path="${file%/*}/"
			cp -lR "${file}" "${path}/hardlink - ${filename}"
		fi
		if [ -d "${file}" ]; then
			filename=$(basename "${file}")
			path="${file%/*}/"
			cp -lR "${file}" "${path}/hardlink - ${filename}"
		fi
done
